### ISSUE TITLE
How to avoid unwanted indentation of email template content?

### ISSUE THREAD

**Issue by kalvinwang** [aliariff/vscode-erb-beautify#68]
I think I'm missing something obvious since this must be a common situation. How can I avoid unwanted indentation of email template content? In the example below, the formatter indented Account ID, but that means Account ID in the email will also be visually indented, which I don't want.

```
* Team ID
<%- if account %>
  * Account ID
<%- end %>
```

Thanks in advance for the help!

**Comment by aliariff** [comment]
It appears that the issue is primarily related to the [`htmlbeautifier`](https://github.com/threedaymonk/htmlbeautifier) project.

nevertheless, some possible options could be
- one liner
`<%= '* Account ID' if account.present? %>`

- avoiding apply automatic formatting for your email files, and adjust manually. (example when your email extension is: `*.text.erb`)
```
"files.associations": {
  "*.text.erb": "plaintext" ==> or something else
}
```
